src/main/java/it/disorganizzazione/progettoweb/persistence/entities/Photo.java
package it.disorganizzazione.progettoweb.persistence.entities;

import java.sql.Timestamp;

public class Photo extends PhotoId {
    private String extension;

    public Photo() {
    }

    public Photo(Integer userId, Timestamp creationTimestamp, String extension) {
        super(userId, creationTimestamp);
        this.extension = extension;
    }

    public static Photo defaultPhoto() {
        return new Photo();
    }

    public String getFilename() {
        return this.creationTimestamp.getTime() + "." + extension;
    }

    public void setExtension(String extension) { this.extension = extension; }

    public String getExtension() { return extension; }

    public String getPath() {
        if (extension != null) return "/photos/" + this.getUserId() + "/" + getFilename();
        else return "/photos/default.jpg";
    }

    @Override
    public String toString(){
        return getPath();
    }
}

src/main/java/it/disorganizzazione/progettoweb/servlets/citizen/HomeServlet.java
package it.disorganizzazione.progettoweb.servlets.citizen;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.BarcodeQRCode;
import com.itextpdf.text.pdf.PdfWriter;
import it.disorganizzazione.commons.persistence.dao.exceptions.DAOException;
import it.disorganizzazione.commons.persistence.dao.exceptions.DAOFactoryException;
import it.disorganizzazione.commons.persistence.dao.factories.DAOFactory;
import it.disorganizzazione.progettoweb.persistence.dao.general.DrugPrescriptionDAO;
import it.disorganizzazione.progettoweb.persistence.entities.prescriptions.DrugPrescription;
import it.disorganizzazione.progettoweb.persistence.entities.prescriptions.PrescriptionId;
import it.disorganizzazione.progettoweb.persistence.entities.users.Citizen;
import it.disorganizzazione.progettoweb.utils.Feedback;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.Objects;

public class HomeServlet extends HttpServlet {
    private DrugPrescriptionDAO drugPrescriptionDAO;

    @Override
    public void init() throws ServletException {
        DAOFactory daoFactory = (DAOFactory) super.getServletContext().getAttribute("daoFactory");
        try {
            drugPrescriptionDAO = daoFactory.getDAO(DrugPrescriptionDAO.class);
        } catch (NullPointerException ex) {
            throw new ServletException("Impossible to get the daoFactory", ex);
        } catch (DAOFactoryException ex) {
            throw new ServletException("Impossible to get DAOs from the the daoFactory", ex);
        }
    }

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        request.getRequestDispatcher("/WEB-INF/citizen/home.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        try {
            if (request.getParameterMap().containsKey("print")) {
                PrescriptionId pid = PrescriptionId.getFromRequest(request);
                DrugPrescription drugPrescription = Objects.requireNonNull(drugPrescriptionDAO.getByPrimaryKey(pid));
                Citizen citizen = (Citizen) Objects.requireNonNull(request.getSession().getAttribute("user"));
                String QRContent = "Prescrizione Numero: " + pid.getUniqueId() + "\nCodice Medico: " + pid.getPlannerId() +
                        "\nCodice Fiscale Paziente: " + citizen.getCf() + "\nData Prescrizione: " + pid.getPrescriptionTimestamp() +
                        "\nDescrizione Farmaco:\n" + drugPrescription.getDescription();

                Document document = new Document();
                response.setContentType("application/pdf");
                response.addHeader("Content-Disposition", "attachment; filename=" + pid.getUniqueId() + ".pdf");
                PdfWriter.getInstance(document, response.getOutputStream());

                document.open();
                Font fontValue = FontFactory.getFont(FontFactory.TIMES, 20, BaseColor.BLACK);
                Font fontTitle = FontFactory.getFont(FontFactory.TIMES_BOLD, 20, BaseColor.BLACK);

                Image QR = new BarcodeQRCode(QRContent, 1000, 1000, null).getImage();
                QR.scaleAbsolute(200, 200);
                float x = (PageSize.A4.getWidth() - QR.getScaledWidth()) / 2;
                QR.setAbsolutePosition(x, QR.getAbsoluteY());

                document.add(QR);
                for (String piece : QRContent.split("\n")) {
                    int indexSeparator = piece.indexOf(":");
                    Paragraph paragraph = new Paragraph();
                    if (indexSeparator != -1) {
                        String title = piece.substring(0, indexSeparator);
                        String value = piece.substring(indexSeparator);

                        paragraph.add(new Chunk(title, fontTitle));
                        paragraph.add(new Chunk(value, fontValue));

                    } else {
                        paragraph.add(new Chunk(piece, fontValue));
                    }
                    paragraph.setMultipliedLeading(3);
                    document.add(paragraph);
                }
                document.close();
            }
        } catch (NullPointerException | IllegalArgumentException ex) {
            ex.printStackTrace();
            Feedback.invalidRequestError("home").forward(request, response);
        } catch (DAOException ex) {
            ex.printStackTrace();
            Feedback.serverError("/").forward(request, response);
        } catch (DocumentException e) {
            e.printStackTrace();
            Feedback.serverError("/").forward(request, response);
        }
    }
}

src/main/java/it/disorganizzazione/progettoweb/servlets/doctor/HomeServlet.java
package it.disorganizzazione.progettoweb.servlets.doctor;

import it.disorganizzazione.commons.persistence.dao.exceptions.DAOException;
import it.disorganizzazione.commons.persistence.dao.exceptions.DAOFactoryException;
import it.disorganizzazione.commons.persistence.dao.factories.DAOFactory;
import it.disorganizzazione.progettoweb.persistence.dao.general.DrugPrescriptionDAO;
import it.disorganizzazione.progettoweb.persistence.dao.general.ExamPrescriptionDAO;
import it.disorganizzazione.progettoweb.persistence.dao.general.PhotoDAO;
import it.disorganizzazione.progettoweb.persistence.dao.general.VisitPrescriptionDAO;
import it.disorganizzazione.progettoweb.persistence.dao.users.CitizenDAO;
import it.disorganizzazione.progettoweb.persistence.entities.prescriptions.DrugPrescriptionView;
import it.disorganizzazione.progettoweb.persistence.entities.prescriptions.ExamPrescriptionView;
import it.disorganizzazione.progettoweb.persistence.entities.prescriptions.VisitPrescriptionView;
import it.disorganizzazione.progettoweb.persistence.entities.users.Citizen;
import it.disorganizzazione.progettoweb.persistence.entities.users.Doctor;
import it.disorganizzazione.progettoweb.utils.Feedback;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.*;

public class HomeServlet extends HttpServlet {

    private CitizenDAO citizenDAO;
    private VisitPrescriptionDAO visitPrescriptionDAO;
    private ExamPrescriptionDAO examPrescriptionDAO;
    private DrugPrescriptionDAO drugPrescriptionDAO;

    @Override
    public void init() throws ServletException {
        DAOFactory daoFactory = (DAOFactory) super.getServletContext().getAttribute("daoFactory");
        try {
            citizenDAO = daoFactory.getDAO(CitizenDAO.class);
            visitPrescriptionDAO = daoFactory.getDAO(VisitPrescriptionDAO.class);
            examPrescriptionDAO = daoFactory.getDAO(ExamPrescriptionDAO.class);
            drugPrescriptionDAO = daoFactory.getDAO(DrugPrescriptionDAO.class);
        } catch (NullPointerException ex) {
            throw new ServletException("Impossible to get the daoFactory", ex);
        } catch (DAOFactoryException ex) {
            throw new ServletException("Impossible to get DAOs from the the daoFactory", ex);
        }
    }

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        Doctor doctor = (Doctor) request.getSession().getAttribute("user");
        try {
            // Attività recenti del dottore
            List<VisitPrescriptionView> visitView = visitPrescriptionDAO.getViewByPlannerId(doctor.getId(),null);
            List<ExamPrescriptionView> examView = examPrescriptionDAO.getViewByPlannerId(doctor.getId(),null);
            List<DrugPrescriptionView> drugView = drugPrescriptionDAO.getViewByPlannerId(doctor.getId(),null);
            if (visitView != null && !visitView.isEmpty())
                request.setAttribute("visitPrescriptionView", visitView.get(visitView.size()-1));
            if (examView != null && !examView.isEmpty())
                request.setAttribute("examPrescriptionView", examView.get(examView.size()-1));
            if (drugView != null && !drugView.isEmpty())
                request.setAttribute("drugPrescriptionView", drugView.get(drugView.size()-1));
            request.getRequestDispatcher("/WEB-INF/doctor/home.jsp").forward(request, response);
        } catch (DAOException ex) {
            ex.printStackTrace();
            Feedback.serverError("/").forward(request, response);
        }
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        Doctor doctor = (Doctor) request.getSession().getAttribute("user");
        try {
            int patientId = Integer.parseInt(request.getParameter("patientId"));
            Citizen patient = citizenDAO.getByPrimaryKey(patientId);
            if (patient.getDoctorId().equals(doctor.getId())) {
                request.getSession().setAttribute("patient", patient);
                response.sendRedirect(response.encodeRedirectURL("visit"));
            } else {
                throw new IllegalArgumentException("Invalid patient");
            }
        } catch (NullPointerException | IllegalArgumentException ex) {
            Feedback.invalidRequestError("home").forward(request, response);
        } catch (DAOException ex) {
            ex.printStackTrace();
            Feedback.serverError("/").forward(request, response);
        }
    }
}

src/main/java/it/disorganizzazione/progettoweb/servlets/pharmacy/HomeServlet.java
package it.disorganizzazione.progettoweb.servlets.pharmacy;

import it.disorganizzazione.commons.persistence.dao.exceptions.DAOException;
import it.disorganizzazione.commons.persistence.dao.exceptions.DAOFactoryException;
import it.disorganizzazione.commons.persistence.dao.factories.DAOFactory;
import it.disorganizzazione.progettoweb.persistence.dao.general.DrugPrescriptionDAO;
import it.disorganizzazione.progettoweb.persistence.entities.prescriptions.DrugPrescriptionView;
import it.disorganizzazione.progettoweb.persistence.entities.prescriptions.PrescriptionId;
import it.disorganizzazione.progettoweb.utils.Feedback;
import it.disorganizzazione.progettoweb.utils.Toast;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public class HomeServlet extends HttpServlet {
    private DrugPrescriptionDAO drugPrescriptionDAO;

    @Override
    public void init() throws ServletException {
        DAOFactory daoFactory = (DAOFactory) super.getServletContext().getAttribute("daoFactory");
        try {
            drugPrescriptionDAO = daoFactory.getDAO(DrugPrescriptionDAO.class);
        } catch (NullPointerException ex) {
            throw new ServletException("Impossible to get the daoFactory", ex);
        } catch (DAOFactoryException ex) {
            throw new ServletException("Impossible to get DAOs from the the daoFactory", ex);
        }
    }

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        request.getRequestDispatcher("/WEB-INF/pharmacy/home.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        if (request.getParameterMap().containsKey("delete")) {
            request.getSession().removeAttribute("receipt");
            Toast.successDrugDelete().setLink("home").redirect(request,response);
            return;
        }
        if (request.getParameterMap().containsKey("forward")) {
            response.sendRedirect(response.encodeRedirectURL("sell"));
            return;
        }
        try {
            PrescriptionId pid = PrescriptionId.getFromRequest(request);
            DrugPrescriptionView drugPrescriptionView = Objects.requireNonNull(drugPrescriptionDAO.getViewByPrimaryKey(pid));

            if (!drugPrescriptionView.getDrugPrescription().isComplete()) {
                List<DrugPrescriptionView> receipt;
                try {
                    receipt = (List<DrugPrescriptionView>) Objects.requireNonNull(request.getSession().getAttribute("receipt"));
                } catch (NullPointerException ex) { /* No drugs selected */
                    receipt = new ArrayList<>();
                }
                receipt.add(drugPrescriptionView);
                request.getSession().setAttribute("receipt", receipt);
                Toast.successDrugAdd().setLink("home").redirect(request,response);

            } else throw new IllegalArgumentException("Invalid prescription");
        } catch (NullPointerException | IllegalArgumentException ex) {
            ex.printStackTrace();
            Feedback.invalidRequestError("home").forward(request, response);
        } catch (DAOException ex) {
            ex.printStackTrace();
            Feedback.serverError("/").forward(request, response);
        }
    }
}

src/main/java/it/disorganizzazione/progettoweb/servlets/specialist/HomeServlet.java
package it.disorganizzazione.progettoweb.servlets.specialist;

import it.disorganizzazione.commons.persistence.dao.exceptions.DAOException;
import it.disorganizzazione.commons.persistence.dao.exceptions.DAOFactoryException;
import it.disorganizzazione.commons.persistence.dao.factories.DAOFactory;
import it.disorganizzazione.progettoweb.persistence.dao.general.VisitPrescriptionDAO;
import it.disorganizzazione.progettoweb.persistence.dao.users.CitizenDAO;
import it.disorganizzazione.progettoweb.persistence.entities.prescriptions.PrescriptionId;
import it.disorganizzazione.progettoweb.persistence.entities.prescriptions.VisitPrescription;
import it.disorganizzazione.progettoweb.persistence.entities.users.Citizen;
import it.disorganizzazione.progettoweb.utils.Feedback;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.Objects;

public class HomeServlet extends HttpServlet {

    private CitizenDAO citizenDAO;
    private VisitPrescriptionDAO visitPrescriptionDAO;

    @Override
    public void init() throws ServletException {
        DAOFactory daoFactory = (DAOFactory) super.getServletContext().getAttribute("daoFactory");
        try {
            citizenDAO = daoFactory.getDAO(CitizenDAO.class);
            visitPrescriptionDAO = daoFactory.getDAO(VisitPrescriptionDAO.class);
        } catch (NullPointerException ex) {
            throw new ServletException("Impossible to get the daoFactory", ex);
        } catch (DAOFactoryException ex) {
            throw new ServletException("Impossible to get DAOs from the the daoFactory", ex);
        }
    }

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        request.getRequestDispatcher("/WEB-INF/specialist/home.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        try {
            PrescriptionId pid = PrescriptionId.getFromRequest(request);
            VisitPrescription visitPrescription = Objects.requireNonNull(visitPrescriptionDAO.getByPrimaryKey(pid));
            Citizen patient = citizenDAO.getByPrimaryKey(Integer.parseInt(request.getParameter("patientId")));
            if (!visitPrescription.isComplete()) {
                request.getSession().setAttribute("patient", patient);
                request.getSession().setAttribute("visitPrescription", visitPrescription);
                response.sendRedirect(response.encodeRedirectURL("visit"));
            } else throw new IllegalArgumentException("Invalid prescription");
        } catch (NullPointerException | IllegalArgumentException ex) {
            ex.printStackTrace();
            Feedback.invalidRequestError("home").forward(request, response);
        } catch (DAOException ex) {
            ex.printStackTrace();
            Feedback.serverError("/").forward(request, response);
        }
    }
}

src/main/webapp/WEB-INF/doctor/home.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="dis" tagdir="/WEB-INF/tags" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<fmt:setLocale value="it_IT"/>
<!DOCTYPE html>
<html>
<dis:head title="Home">
    <link rel="stylesheet" type="text/css" href="<c:url value="/assets/DataTables/datatables.min.css"/>"/>
</dis:head>
<body id="page-top">
<div id="wrapper">
    <dis:sidebar selected="home"/>
    <div class="d-flex flex-column" id="content-wrapper">
        <div id="content">
            <dis:top-nav/>
            <div class="container-fluid">
                <div class="card shadow my-3">
                    <div class="card-header py-3">
                        <p class="text-primary m-0 font-weight-bold">
                            <i class="fas fa-hand-holding-heart mr-2"></i>I miei Pazienti</p>
                    </div>
                    <div class="card-body" style="overflow: hidden;">
                        <table id="patients-table" class="table dataTable my-0 dtr-inline" style="width:100%">
                            <thead>
                            <tr>
                                <th>Nome</th>
                                <th>Codice Fiscale</th>
                                <th>Data di Nascita</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card shadow my-3">
                    <div class="card-header py-3">
                        <p class="text-primary m-0 font-weight-bold"><i
                                class="fas fa-history rounded mr-2"></i>Attivitá recenti</p>
                    </div>
                    <div class="card-body" style="overflow: hidden;">
                        <table class="table my-0 dtr-inline" style="width:100%">
                            <thead>
                            <tr>
                                <th>Paziente</th>
                                <th>Prescrizione</th>
                                <th>Prescritta il</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <c:choose>
                                    <c:when test="${requestScope.visitPrescriptionView != null}">
                                        <td>
                                            <div class="d-flex">
                                                <div class="rounded-circle align-self-center mr-2" style="background-image:url('<c:url value="${requestScope.visitPrescriptionView.patientPhoto.path}"/>');background-size:cover;background-position:center;height:34px;width:34px;flex:none;">
                                                </div><span class="align-self-center mr-3">${requestScope.visitPrescriptionView.patient.name} ${requestScope.visitPrescriptionView.patient.surname}</span>
                                            </div>
                                        </td>
                                        <td><i class="fas fa-stethoscope mr-2"></i>${requestScope.visitPrescriptionView.visitName}</td>
                                        <td><fmt:formatDate value="${requestScope.visitPrescriptionView.visitPrescription.prescriptionTimestamp}"
                                                            pattern="dd MMM yyyy HH:mm"/></td>
                                    </c:when>
                                    <c:otherwise>
                                        <td colspan="3" class="text-center">
                                            <i class="fas fa-stethoscope mr-2"></i>Nessuna visita prescritta</td>
                                    </c:otherwise>
                                </c:choose>
                            </tr>
                            <tr>
                                <c:choose>
                                    <c:when test="${requestScope.examPrescriptionView != null}">
                                        <td>
                                            <div class="d-flex">
                                                <div class="rounded-circle align-self-center mr-2" style="background-image:url('<c:url value="${requestScope.examPrescriptionView.patientPhoto.path}"/>');background-size:cover;background-position:center;height:34px;width:34px;flex:none;">
                                                </div><span class="align-self-center mr-3">${requestScope.examPrescriptionView.patient.name} ${requestScope.examPrescriptionView.patient.surname}</span>
                                            </div>
                                        </td>
                                        <td><i class="fas fa-file-medical-alt mr-2"></i>${requestScope.examPrescriptionView.examName}</td>
                                        <td><fmt:formatDate value="${requestScope.examPrescriptionView.examPrescription.prescriptionTimestamp}"
                                                            pattern="dd MMM yyyy HH:mm"/></td>
                                    </c:when>
                                    <c:otherwise>
                                        <td colspan="3" class="text-center">
                                            <i class="fas fa-file-medical-alt mr-2"></i>Nessun esame prescritto</td>
                                    </c:otherwise>
                                </c:choose>
                            </tr>
                            <tr>
                            <c:choose>
                                <c:when test="${requestScope.drugPrescriptionView != null}">
                                    <td>
                                        <div class="d-flex">
                                            <div class="rounded-circle align-self-center mr-2" style="background-image:url('<c:url value="${requestScope.drugPrescriptionView.patientPhoto.path}"/>');background-size:cover;background-position:center;height:34px;width:34px;flex:none;">
                                            </div><span class="align-self-center mr-3">${requestScope.drugPrescriptionView.patient.name} ${requestScope.drugPrescriptionView.patient.surname}</span>
                                        </div>
                                    </td>
                                    <td><i class="fas fa-prescription-bottle mr-2"></i>${requestScope.drugPrescriptionView.drugPrescription.description}</td>
                                    <td><fmt:formatDate value="${requestScope.drugPrescriptionView.drugPrescription.prescriptionTimestamp}"
                                                        pattern="dd MMM yyyy HH:mm"/></td>
                                </c:when>
                                <c:otherwise>
                                    <td colspan="3" class="text-center">
                                        <i class="fas fa-prescription-bottle mr-2"></i>Nessuna ricetta prescritta</td>
                                </c:otherwise>
                            </c:choose>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <dis:footer/>
    </div>
    <a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a>
</div>
<dis:scripts>
    <dis:datatable/>
    <script>
        const patientsTable = {
            ajax: {
                url: '<c:url value="/services/dataTable?dt=user&search=${sessionScope.user.id}"/>',
                dataSrc: 'results'
            }, columns: [
                {
                    data: 'patient',
                    render: renderDT.userWithPhoto('patientProvince', 'patientPhoto')
                },
                {
                    data: 'patient.cf',
                },
                {
                    data: 'patient.birthDate',
                    render: renderDT.date
                },
                {
                    data: 'patient',
                    render: renderDT.doctorButton
                },
            ]
        };
    </script>
    <dis:make-datatable elementId="patients-table" params="patientsTable"/>
</dis:scripts>
</body>
</html>